export const ZodiacPreviewSamples = [
  {
    id: "zodiac-general",
    channelName: "Общий гороскоп",
    channelSlug: "zodiac-general",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♈️ ♉️ ♊️ Энергия дня для всех знаков",
    textExcerpt: "Сегодня Луна переходит в знак Близнецов, принося с собой легкую и коммуникативную энергию. Это отличное время для новых знакомств и обмена идеями. Главное — не распыляться на мелочи и доводить начатое до конца. Вечером уделите время себе.",
    detectedStructure: ["Вводная", "Энергия", "Совет", "CTA"],
    qualityScore: 95,
    scoreBreakdown: {
      structure: 20,
      signUniqueness: 20,
      cta: 15,
      safety: 20,
      repetition: 10,
      telegramReadiness: 10
    },
    riskFlags: [],
    manualReviewNotes: "Структура соблюдена. Пост выглядит гармонично. CTA встроен мягко.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "aries",
    channelName: "Овен",
    channelSlug: "aries",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♈️ Овен: Гороскоп на сегодня",
    textExcerpt: "Ваша марсианская энергия сегодня на пике. Не бойтесь брать инициативу в свои руки — на работе ваши идеи будут услышаны. В личной жизни возможен неожиданный поворот. Доверяйте интуиции.",
    detectedStructure: ["Вводная", "Энергия", "Любовь/Деньги", "Совет", "CTA"],
    qualityScore: 92,
    scoreBreakdown: {
      structure: 20,
      signUniqueness: 20,
      cta: 12,
      safety: 20,
      repetition: 10,
      telegramReadiness: 10
    },
    riskFlags: ["Слабый CTA"],
    manualReviewNotes: "Текст хороший, но CTA можно сделать чуть заметнее, не нарушая Tone of Voice.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "taurus",
    channelName: "Телец",
    channelSlug: "taurus",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♉️ Телец: Гороскоп на сегодня",
    textExcerpt: "День обещает быть стабильным. Постарайтесь не торопиться с финансовыми решениями. Венера покровительствует уюту, поэтому вечер лучше провести дома с близкими людьми.",
    detectedStructure: ["Вводная", "Деньги", "Совет", "CTA"],
    qualityScore: 90,
    scoreBreakdown: {
      structure: 18,
      signUniqueness: 20,
      cta: 15,
      safety: 17,
      repetition: 10,
      telegramReadiness: 10
    },
    riskFlags: [],
    manualReviewNotes: "Совет про финансы звучит безопасно, без гарантий.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "gemini",
    channelName: "Близнецы",
    channelSlug: "gemini",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♊️ Близнецы: Гороскоп на сегодня",
    textExcerpt: "Ваш управитель Меркурий сегодня активен. Ожидайте много общения и новой информации. Обратите внимание на входящие сообщения, возможно, одно из них скрывает важную подсказку.",
    detectedStructure: ["Вводная", "Энергия", "Совет", "CTA"],
    qualityScore: 85,
    scoreBreakdown: {
      structure: 15,
      signUniqueness: 20,
      cta: 15,
      safety: 20,
      repetition: 5,
      telegramReadiness: 10
    },
    riskFlags: ["Повторяется аффирмация"],
    manualReviewNotes: "Аффирмация совпадает с постом двухдневной давности. Требуется перегенерация.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "cancer",
    channelName: "Рак",
    channelSlug: "cancer",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♋️ Рак: Гороскоп на сегодня",
    textExcerpt: "Луна усиливает вашу эмпатию. Вы будете тонко чувствовать настроение окружающих. Используйте это для налаживания отношений на работе.",
    detectedStructure: ["Вводная", "Энергия", "Работа", "Совет", "CTA"],
    qualityScore: 94,
    scoreBreakdown: {
      structure: 19,
      signUniqueness: 20,
      cta: 15,
      safety: 20,
      repetition: 10,
      telegramReadiness: 10
    },
    riskFlags: [],
    manualReviewNotes: "Хороший пост, без замечаний.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "leo",
    channelName: "Лев",
    channelSlug: "leo",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♌️ Лев: Гороскоп на сегодня",
    textExcerpt: "Ваша харизма сегодня открывает любые двери. Если вы планировали важный разговор — самое время его начать. Звезды на вашей стороне в творческих начинаниях.",
    detectedStructure: ["Вводная", "Энергия", "Работа", "Совет", "CTA"],
    qualityScore: 88,
    scoreBreakdown: {
      structure: 20,
      signUniqueness: 20,
      cta: 15,
      safety: 18,
      repetition: 10,
      telegramReadiness: 5
    },
    riskFlags: ["Слишком длинный пост"],
    manualReviewNotes: "Пост получился объемным. Можно сократить пару предложений для лучшей читаемости в Telegram.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "virgo",
    channelName: "Дева",
    channelSlug: "virgo",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♍️ Дева: Гороскоп на сегодня",
    textExcerpt: "День подходит для структурирования мыслей и наведения порядка в делах. Ваш аналитический ум поможет решить сложную задачу.",
    detectedStructure: ["Вводная", "Энергия", "Работа", "Совет", "CTA"],
    qualityScore: 91,
    scoreBreakdown: {
      structure: 19,
      signUniqueness: 20,
      cta: 15,
      safety: 17,
      repetition: 10,
      telegramReadiness: 10
    },
    riskFlags: [],
    manualReviewNotes: "Фокус на работу и порядок отлично подходит знаку.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "libra",
    channelName: "Весы",
    channelSlug: "libra",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♎️ Весы: Гороскоп на сегодня",
    textExcerpt: "Поиск баланса сегодня увенчается успехом. Возможны приятные сюрпризы в личной жизни. Постарайтесь избегать конфликтов и острых углов.",
    detectedStructure: ["Вводная", "Энергия", "Любовь", "Совет", "CTA"],
    qualityScore: 93,
    scoreBreakdown: {
      structure: 20,
      signUniqueness: 15,
      cta: 15,
      safety: 20,
      repetition: 13,
      telegramReadiness: 10
    },
    riskFlags: ["Нет различия знака"],
    manualReviewNotes: "Текст хороший, но немного не хватает уникальных якорей Весов, помимо слова 'баланс'.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "scorpio",
    channelName: "Скорпион",
    channelSlug: "scorpio",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♏️ Скорпион: Гороскоп на сегодня",
    textExcerpt: "Ваша интуиция сегодня работает как радар. Вы сможете разгадать чужие мотивы и скрытые намерения. Используйте это знание во благо.",
    detectedStructure: ["Вводная", "Энергия", "Совет", "CTA"],
    qualityScore: 89,
    scoreBreakdown: {
      structure: 18,
      signUniqueness: 20,
      cta: 15,
      safety: 20,
      repetition: 10,
      telegramReadiness: 6
    },
    riskFlags: ["Слишком длинный пост"],
    manualReviewNotes: "Хорошая привязка к глубине знака. Чуть сократить вводную часть.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "sagittarius",
    channelName: "Стрелец",
    channelSlug: "sagittarius",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♐️ Стрелец: Гороскоп на сегодня",
    textExcerpt: "Сегодня вас гарантированно ждет огромный успех в финансах и работе. Вы точно получите повышение.",
    detectedStructure: ["Вводная", "Энергия"],
    qualityScore: 50,
    scoreBreakdown: {
      structure: 10,
      signUniqueness: 10,
      cta: 0,
      safety: 0,
      repetition: 20,
      telegramReadiness: 10
    },
    riskFlags: ["Гарантированное предсказание", "Финансовая гарантия", "Нет CTA"],
    manualReviewNotes: "Грубое нарушение safety-правил. Обещания 100% успеха недопустимы. Блокировка.",
    status: "Live заблокирован",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "capricorn",
    channelName: "Козерог",
    channelSlug: "capricorn",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♑️ Козерог: Гороскоп на сегодня",
    textExcerpt: "Дисциплина и упорство принесут свои плоды. Не отступайте от намеченного плана, даже если обстоятельства пытаются сбить вас с пути.",
    detectedStructure: ["Вводная", "Энергия", "Работа", "Совет", "CTA"],
    qualityScore: 95,
    scoreBreakdown: {
      structure: 20,
      signUniqueness: 20,
      cta: 15,
      safety: 20,
      repetition: 10,
      telegramReadiness: 10
    },
    riskFlags: [],
    manualReviewNotes: "Отличный пост, отражающий суть знака.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "aquarius",
    channelName: "Водолей",
    channelSlug: "aquarius",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♒️ Водолей: Гороскоп на сегодня",
    textExcerpt: "Нестандартные идеи сегодня будут рождаться одна за другой. Запишите их, они могут пригодиться в будущем. Вечер идеален для встречи с друзьями.",
    detectedStructure: ["Вводная", "Энергия", "Совет", "CTA"],
    qualityScore: 90,
    scoreBreakdown: {
      structure: 20,
      signUniqueness: 20,
      cta: 10,
      safety: 20,
      repetition: 10,
      telegramReadiness: 10
    },
    riskFlags: ["Слабый CTA"],
    manualReviewNotes: "Все хорошо, кроме невнятного призыва к действию в конце.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  },
  {
    id: "pisces",
    channelName: "Рыбы",
    channelSlug: "pisces",
    source: "dry-run preview sample",
    sampleDate: "2026-06-22",
    previewMode: "read-only",
    title: "♓️ Рыбы: Гороскоп на сегодня",
    textExcerpt: "Прислушайтесь к своим снам — сегодня они могут быть вещими. Ваш творческий потенциал высок, уделите время любимому хобби.",
    detectedStructure: ["Вводная", "Энергия", "Совет", "CTA"],
    qualityScore: 96,
    scoreBreakdown: {
      structure: 20,
      signUniqueness: 20,
      cta: 15,
      safety: 20,
      repetition: 11,
      telegramReadiness: 10
    },
    riskFlags: ["Повторяется совет"],
    manualReviewNotes: "Совет про хобби был недавно. Желательно немного видоизменить.",
    status: "На ручной просмотр",
    safetyNote: "Санитизированный пример по структуре dry-run. Live-публикация отключена."
  }
];
